[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
# fallback_oz = true

[profile.default.zksync]
# enable_eravm_extensions = true # Note: System contract calls (NonceHolder and ContractDeployer) can only be called with this set to true
zksolc = "1.5.7"

#[etherscan]
abstractTestnet = { chain = "11124", url = "https://api-sepolia.abscan.org/api", key = "TACK2D1RGYX9U7MC31SZWWQ7FCWRYQ96AD"} # You can replace these values or leave them blank to override via CLI
#abstractMainnet = { chain = "2741", url = "", key = ""} # You can replace these values or leave them blank to override via CLI